version: "3.9"
services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    profiles: ["local"]
    expose:
      - "8545"
    ports:
      - "8545:8545"
    command: ["anvil --host 0.0.0.0 --port 8545"]

  relayer:
    image: relayer:latest
    profiles: ["local", "development"]
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - API_KEY=${BONSAI_API_KEY}
      - RUST_LOG=info
    entrypoint:
      - ethereum-relay
      - --bonsai-url
      - ${BONSAI_API_URL}
      - --proxy-address
      - ${RELAY_CONTRACT_ADDRESS}
      - --eth-node-url
      - ${ETH_WS_NODE_URL}
      - --wallet-key-identifier
      - ${PRIVATE_KEY}
      - --eth-chain-id
      - ${ETH_CHAIN_ID}
    depends_on:
      - anvil

  contract-deployer:
    image: ghcr.io/foundry-rs/foundry:latest
    profiles: ["local", "development"]
    working_dir: /src
    volumes:
      - .:/src
    command: ["forge create --force --rpc-url ${ETH_HTTP_NODE_URL} --private-key ${PRIVATE_KEY} ${CONTRACT_PATH} --constructor-args ${CONSTRUCTOR_ARGS}"]
    depends_on:
      - anvil
