[package]
name = "bonsai-ethereum-cli"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bonsai-sdk = { package = "bonsai-sdk", git = "https://github.com/risc0/risc0", branch = "main" }
bonsai-starter-methods = { path = "../methods"}
clap = { version = "4.3", features = ["derive", "env"] }
hex = "0.4.3"
risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "b35e1faa37fb4b60cf8dd849cf46b14d1713c881" }

[features]
solidity_compile = []