[package]
name = "bonsai_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
reqwest = { version = "0.11", features = ["json", "blocking"], optional = true }

[features]
default = ["sdk"]
sdk = ["dep:reqwest"]